damage-on-damage: 10 #сколько урона получит игрок, если получит урон во время полёта?
reduce-durability: 1 #на сколько уменьшать прочность элитр во время полёта? Рекомендуется 1-3
remove-if-broken: false #забирать элитру, если она сломалась во время полёта? default: false
##############################################################
# Настройте сообщения вывода плагина с поддержкой Hex цветов #
##############################################################
messages: #сообщения плагина
  fly-on: '&#69f581Вы включили режим полёта!'
  fly-off: '&#69f581Вы выключили режим полёта!'
  no-elytra: '&#d42828Наденьте Элитру чтобы летать!'
  config-reload: '&#4dc2e3Конфигурация перезагружена!'
  command-no-args: '&#d42828Недостаточно аргументов'
  get-damage-on-fly: '&#d42828Вы получили урон! Режим полёта выключен!'
  damage-on-fly: '&#d42828Вы нанесли урон! Режим полёта выключен!'


